file_test/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('service.urls', namespace='service')),
]

if settings.DEBUG:     
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )   
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

service/urls.py
from django.urls import path

from . import views


app_name = 'service' 

urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.upload_file, name='upload'),
    path('user_files/', views.user_files, name='user_files'),
    path('download/<int:file_id>/', views.download_file, name='download'),
]

service/models.py
from django.conf import settings
from django.contrib.auth import get_user_model 
from django.core.validators import MaxValueValidator
from django.db import models

User = get_user_model()


class UploadedFile(models.Model):
    name = models.CharField(max_length=255, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='files')
    size = models.PositiveIntegerField(
        validators=[MaxValueValidator(settings.MAX_FILE_SIZE)]
    )

    @property
    def archive_name(self):
        name = '.'.join(self.name.split('.')[:-1])
        return f'{name}.zip'


class FileChunk(models.Model):
    file = models.ForeignKey(UploadedFile, on_delete=models.CASCADE,
                             related_name='chunks')
    index = models.PositiveSmallIntegerField(
        validators=[MaxValueValidator(settings.MAX_FILE_CHUNKS_COUNT)]
    )
    size = models.PositiveIntegerField(
        validators=[MaxValueValidator(settings.MAX_CHUNK_SIZE)]
    )

    class Meta:
        ordering = ['-index']
        constraints = [
            models.UniqueConstraint(
                fields=['file', 'index'],
                name='file_chunk_index_unique'
            )
        ]

service/forms.py
from django import forms

from service.validators import max_file_size, unique_file_name


class UploadFileForm(forms.Form):
    file = forms.FileField(validators=[max_file_size, unique_file_name])

service/views.py
import logging

from django.contrib.auth.decorators import login_required 
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404

from service.forms import UploadFileForm
from service.models import UploadedFile
from service.utils import handle_uploaded_file, get_file_for_download


logger = logging.getLogger(__name__)


def index(request):
    return render(request, 'service/index.html')


@login_required
def upload_file(request):
    form = UploadFileForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        file = request.FILES['file']

        logger.debug(f'User ID: {request.user.id}. '
                     f'Starting uploading file {file.name}.')
        try:
            handle_uploaded_file(file, request)
        except Exception:
            message = f'Something went wrong with uploading file {file.name}.'
            logger.exception(f'User ID: {request.user.id}. {message}')
            return render(request, 'service/message.html', {'message': message})
        message = f'Successfully uploaded file {file.name}'
        return render(request, 'service/message.html', {'message': message})
    if request.method == 'POST':
        logger.warning(f'User ID: {request.user.id}. '
                       f'Error in File Form validation: {form.errors.as_data()}.')
    return render(request, 'service/upload.html', {'form': form})


@login_required
def download_file(request, file_id):
    file = get_object_or_404(UploadedFile, id=file_id)
    if request.user != file.author:
        logger.warning(
            f'User ID: {request.user.id}. '
            f'Not author tryed to download file. File made by {file.author.id}'
        )
        return redirect('service:index')

    logger.debug(f'User ID: {request.user.id}. '
                 f'Starting downloading file {file.name}.')
    try:
        prepared_file = get_file_for_download(file)
    except Exception:
        message = f'Something went wrong with downloading file {file.name}.'
        logger.exception(f'User ID: {request.user.id}. {message}')
        return render(request, 'service/message.html', {'message': message})

    response = HttpResponse(prepared_file.getvalue(), content_type='application/force-download')
    if not file.name.isascii():
        logger.info(
            f'User ID: {request.user.id}. Downloading file with non ascii format. '
            f'The name of the downloaded file will be incorrect. File name is: {file.name}.'
        )
    response['Content-Disposition'] = f'attachment; filename="{file.name}"'
    return response


@login_required
def user_files(request):
    files = request.user.files.all()
    return render(request, 'service/download.html', {'files': files})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <main>
            {% block content %}{% endblock %} 
        </main>
    </body>
</html>

templates/includes/form.html
{% for field in form %}
    <div>
        {% if form.errors %} 
            {% for field in form %}
                {% for error in field.errors %}
                    <div>
                        {{ error|escape }}
                    </div>   
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div>
                    {{ error|escape }}
                </div>
            {% endfor %}
        {% endif %}


        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
            <p>{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor %}

templates/service/download.html
{% extends 'base.html' %} 

{% block title %}Download{% endblock %}

{% block content%}
    <a href={% url 'service:index' %}>Main page</a>
    <h1>My files</h1>
    <h4>Click on file name to download it<h4>
    <ul>
        {% for file in files %}
            <li>
                <a href={% url 'service:download' file_id=file.id %}>{{ file.name }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/service/index.html
{% extends 'base.html' %} 

{% block title %}Main page{% endblock %}

{% block content%}
    <a href={% url 'service:upload' %}>Upload file</a>
    <a href={% url 'service:user_files' %}>List of my files</a>
{% endblock %}

templates/service/message.html
{% extends 'base.html' %} 

{% block title %}Message{% endblock %}

{% block content%}
    <h1>{{ message }}</h1>
    <a href={% url 'service:index' %}>Main page</a>
{% endblock %}

templates/service/success.html
{% extends 'base.html' %} 

{% block title %}Success{% endblock %}

{% block content%}
    <p>Successfully uploaded file {{ file_name }}</p>
    <a href={% url 'service:index' %}>Main page</a>
{% endblock %}

templates/service/upload.html
{% extends 'base.html' %} 

{% block title %}Upload file{% endblock %}

{% block content%}
    <form method='post' action={% url 'service:upload' %} enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <div>
            <button type="submit">
                Upload
            </button>
        </div>
    </form>
{% endblock %}